spring:
  redis:
    lettuce:
      pool:
        max-idle: 2
        max-active: 2
        min-idle: 0
        max-wait: 1ms
    host: localhost
    port: 6379
hbase:
  conf:
    config-map:
      'hbase.zookeeper.quorum':'zookeeper'
      'hbase.zookeeper.property.clientPort':'2181'